builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
      - linux_arm
      - windows_amd64
    main: ./
    ldflags:
      - -extldflags '-static'
      - -s -w -X 'github.com/fitz7/tfnew/cmd.Version={{.Version}}'

archives:
  - format: binary
    name_template: '{{ .Binary }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_checksums.txt'
