name: Checks
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: go-with-cache
        uses: magnetikonline/action-golang-cache@v4
        with:
          go-version-file: go.mod
      - run: make install-tools
      - run: make lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: go-with-cache
        uses: magnetikonline/action-golang-cache@v4
        with:
          go-version-file: go.mod
      - run: make install-tools
      - run: make test
